### ISSUE TITLE
Fix IML ZFS features and re-enable SSI testing with ZFS devices

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#278]
Due to the issue described in #244 introduced because of the enforcement of ZFS MMP in 2.10 release of Lustre, ZFS testing was failing and needed to be disabled. This issues describes the work and progress of the various tasks required to fix the IML ZFS functionality and to re-enable ZFS SSI testing.

----
- [x] Remedy situation where secondary node cannot discover new datasets #244 #314 
  - [x] Store Zpool state when pool is discovered
  - [x] Read Zpool state from store when pool is reported as UNAVAIL
  - [x] Export Zpool between discovery of VolumeNodes for primary and secondary mounts
  - [x] Export Zpool between manager jobs on target
  - [x] Re-enable ZFS SSI testing
  - [x] Workaround bug #282 in test framework
  - [x] Pin iml-common version 1.1 (after merging #191 )
     - [x] Update import calls to remove use of pacemaker_ha_operation parameter #262 
  - [x] Skip test in sim temporarily #301 
  - [x] Skip test in ssi temporarily #298  
----
- [x] Upload python2-iml-common1.1 to COPR
  - [x] Remove 'force' flag from Zpool import calls https://github.com/intel-hpdd/iml-common/pull/17
  - [x] Remove 'pacemaker-ha-operation' parameter (now redundant) from target import method https://github.com/intel-hpdd/iml-common/pull/18
  - [x] Tag and deploy iml-common 1.1.0 to PyPi
  - [x] Add iml-common spec file to MFL dependencies to create COPR package names including version https://github.com/intel-hpdd/manager-for-lustre-dependencies/pull/36
  - [x] Upload python2-iml-common1.0 to COPR
  - [x] Upload python2-iml-common1.1 to COPR
----
- [x] Update IML repo to use a pinned version of iml-common (1.0) #191 
----
*OUTSTANDING ISSUES TO BE FIXED BEFORE 4.0 RELEASE*
- [x] Remove store on teardown, clear on start-up of agent https://github.com/intel-hpdd/iml-common/pull/19
  - [ ] Fix file conflicts in iml-common rpm upgrades https://github.com/intel-hpdd/manager-for-lustre-dependencies/pull/55
  - [x] Bump iml-common to 1.1.1 https://github.com/intel-hpdd/manager-for-lustre-dependencies/pull/58
  - [x] Push 1.1.1-1 to COPR
- [x] Set hostid in EFS test suite #296  
- [x] Fix unit tests
- [x] Fix sim tests (with the exception #301 )
----
*POST 4.0 RELEASE*
- [ ] Investigate https://github.com/intel-hpdd/intel-manager-for-lustre/issues/289
- [x] Fix exception #298 
- [ ] Fix exception #301 
- [x] Fix location of store file https://github.com/intel-hpdd/intel-manager-for-lustre/issues/290
- [x] Scan all pools regardless of state #292
