### ISSUE TITLE
Move to reactive architecture for Devices + ZFS - Part 1

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/intel-manager-for-lustre#280]
## Background

IML currently does manual introspection to discover device info + ZFS pool / dataset info and props.

This means that IML is responsible for discovering current state. 

In other words, we own + maintain code to poll and scrape files to build a picture.

The current architecture is bottom-up with a device scan scheduled which in turn discovers state.
This means every time we scan we are doing the same work to discover if anything changed (poll-based).

This is naturally less efficient than a push-based reactive architecture where IML is alerted to changes in state and otherwise is quiet. This could be thought of as a top-down architecture.

As we look to scale and for generally not implementing redundant code that is implemented at the OS level, we should move to a push-based architecture.

Given this is effectively flipping the process of state discovery on it's head; it's something that should be attempted in phases. This issue will cover the 1st phase

## Work Currently Needed

- [x] #19 Add device-scanner as agent dep
  - Even though the device scanner is capable of streaming updates over sockets
     The agent is currently poll based. Because of that, this first pass of integration
     will just drop the manual introspection code in favor of reading current state from
     the scanner.
- [x] https://github.com/intel-hpdd/device-scanner/pull/25 Create First pass of ZED integration
  - Implement ZED in the device scanner. Further work will consume these changes in the agent.
- [x] Implement node-libzfs in device-scanner to get relevant info on first boot.
- [x] #131 Consume device-scanner ZED changes in agent (partially complete but not landed - implement in manager)
- [x] https://github.com/intel-hpdd/intel-manager-for-lustre/issues/403 Map ZFS objects to hosts that can access shared storage (work to be abandoned - probably implement in manager)
- [x] #337 remove DM (complete but not landed - implement in manager)
- [x] #372 Move mdraid and emcpowers module functionality into device-scanner (complete but not landed - implement in manager)

**Comment by jgrund** [comment]
Closing to have one ticket to track.
